// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"time"
)

type Order struct {
	ID              int32       `json:"id"`
	UserID          int32       `json:"user_id"`
	ProductID       int32       `json:"product_id"`
	Quantity        int32       `json:"quantity"`
	TotalPrice      int32       `json:"total_price"`
	ToLocation      string      `json:"to_location"`
	IsDraft         bool        `json:"is_draft"`
	IsPayed         bool        `json:"is_payed"`
	IsShipped       bool        `json:"is_shipped"`
	CurrentLocation interface{} `json:"current_location"`
}

type Product struct {
	ID          int32     `json:"id"`
	Title       string    `json:"title"`
	Price       int32     `json:"price"`
	Description string    `json:"description"`
	Image0      string    `json:"image_0"`
	Image1      string    `json:"image_1"`
	Image2      string    `json:"image_2"`
	Image3      string    `json:"image_3"`
	CreatedAt   time.Time `json:"created_at"`
	ValidUntil  time.Time `json:"valid_until"`
}

type User struct {
	ID          int32  `json:"id"`
	Username    int32  `json:"username"`
	EncodedHash string `json:"encoded_hash"`
	PhoneNumber string `json:"phone_number"`
	Email       string `json:"email"`
	Address     string `json:"address"`
}
