// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package db

import (
	"context"
)

type Querier interface {
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	GetOrder(ctx context.Context, id int32) (Order, error)
	GetProduct(ctx context.Context, id int32) (Product, error)
	ListOrders(ctx context.Context) ([]Order, error)
	ListProducts(ctx context.Context) ([]Product, error)
}

var _ Querier = (*Queries)(nil)
